spring:
  profiles:
    active:
      - local

security:
  jwt:
    token:
      secret-key: kksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabo
      expire-length: 3600000

url:
  moim: /darakbang/%d/moim/%d
  chat: /darakbang/%d/chat/%d
  chatroom: /darakbang/%d/chatting-room/%d
