name: cd-prod

on:
  push:
    branches:
      - secret

jobs:
  deploy:
    runs-on: prod

    steps:
      - name: add permission to runner
        run: |
          chown -R ubuntu:ubuntu /home/ubuntu/actions-runner
          chown -R ubuntu:ubuntu /home/ubuntu/deploy

      - name: create secret to deploy.sh
        run: |
          printf "%s" "${{ secrets.UPDATED_SCRIPT }}" | sed 's/\$/\\$/g' > deploy.sh
          cat deploy.sh

      - name: move deploy.sh to /home/ubuntu/deploy
        run: |
          mv deploy.sh /home/ubuntu/deploy/deploy1.sh
          cat /home/ubuntu/deploy/deploy1.sh

      - name: add permission to deploy.sh
        run: |
          chown -R ubuntu:ubuntu /home/ubuntu/deploy/deploy1.sh
          chmod +x /home/ubuntu/deploy/deploy.sh

      - name: run deploy.sh
        run: |
          cd /home/ubuntu/deploy
          ./deploy1.sh
